/**
 * Generates the phone's team builder data (decision D-36) into
 * `apps/web/public/data/teambuilder.json` (git-ignored): legal species with their legal moves,
 * items, abilities and natures for the Casual ruleset, straight from the Showdown dex.
 *
 * Runs before `pnpm dev` / `pnpm build`. Skips the work (≈ 8 s) when the file was generated by the
 * same `pokemon-showdown` version and generator version; `--force` rebuilds anyway.
 */
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { gzipSync } from 'node:zlib';
import type { TeamBuilderData } from '@poke-air/shared';
import { PUBLIC_DIR } from './lib/download.js';

const OUTPUT_DIR = join(PUBLIC_DIR, 'data');
const OUTPUT = join(OUTPUT_DIR, 'teambuilder.json');

async function currentStamp(): Promise<string> {
  // Resolved from core, which owns the pinned `pokemon-showdown` dependency.
  const require = createRequire(import.meta.resolve('@poke-air/core'));
  const pkg = JSON.parse(
    await readFile(require.resolve('pokemon-showdown/package.json'), 'utf8'),
  ) as { version: string };
  const { TEAM_BUILDER_DATA_VERSION } = await import('@poke-air/core');
  return `${pkg.version}:${TEAM_BUILDER_DATA_VERSION}`;
}

async function existingStamp(): Promise<string | null> {
  try {
    const data = JSON.parse(await readFile(OUTPUT, 'utf8')) as Pick<TeamBuilderData, 'stamp'>;
    return data.stamp;
  } catch {
    return null;
  }
}

const stamp = await currentStamp();
if (!process.argv.includes('--force') && (await existingStamp()) === stamp) {
  console.log(`Team builder data is up to date (${stamp}).`);
} else {
  const started = Date.now();
  console.log('Building team builder data from the Showdown dex…');
  const { buildTeamBuilderData } = await import('@poke-air/core');
  const data = buildTeamBuilderData(stamp);
  const json = JSON.stringify(data);
  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(OUTPUT, json);
  const kb = (bytes: number) => `${Math.round(bytes / 1024)} KB`;
  console.log(
    `  ${data.species.length} species, ${data.moves.length} moves, ${data.items.length} items · ` +
      `${kb(json.length)} (${kb(gzipSync(json).length)} gzip) · ${Date.now() - started} ms`,
  );
}
