import {
  TEAM_BUILDER_DATA_URL,
  toId,
  type DexItem,
  type DexMove,
  type DexNature,
  type DexSpecies,
  type TeamBuilderData,
} from '@poke-air/shared';
import { useSyncExternalStore } from 'react';

/**
 * The team builder's dex (generated by `pnpm build:data`, docs/13-phase-2-plan.md § B3), loaded
 * once per page the first time a component asks for it, with lookup indexes by Showdown id.
 */
export interface TeamDex {
  data: TeamBuilderData;
  species: DexSpecies[];
  moves: DexMove[];
  items: DexItem[];
  natures: DexNature[];
  speciesById: Map<string, DexSpecies>;
  moveById: Map<string, DexMove>;
  itemById: Map<string, DexItem>;
  natureById: Map<string, DexNature>;
}

export type TeamDexState =
  { status: 'loading' } | { status: 'ready'; dex: TeamDex } | { status: 'failed' };

let state: TeamDexState = { status: 'loading' };
let requested = false;
const listeners = new Set<() => void>();

function publish(next: TeamDexState): void {
  state = next;
  for (const listener of listeners) listener();
}

function index(data: TeamBuilderData): TeamDex {
  const byId = <T extends { name: string }>(list: T[]) =>
    new Map(list.map((entry) => [toId(entry.name), entry]));
  return {
    data,
    species: data.species,
    moves: data.moves,
    items: data.items,
    natures: data.natures,
    speciesById: byId(data.species),
    moveById: byId(data.moves),
    itemById: byId(data.items),
    natureById: byId(data.natures),
  };
}

function load(): void {
  if (requested) return;
  requested = true;
  fetch(TEAM_BUILDER_DATA_URL)
    .then((response) => {
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return response.json() as Promise<TeamBuilderData>;
    })
    .then((data) => publish({ status: 'ready', dex: index(data) }))
    .catch(() => {
      requested = false; // Let a later mount retry.
      publish({ status: 'failed' });
    });
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  load();
  return () => listeners.delete(listener);
}

/** Loads the dex on first use; re-renders when it arrives (or fails). */
export function useTeamDex(): TeamDexState {
  return useSyncExternalStore(
    subscribe,
    () => state,
    () => state,
  );
}

/** Moves a species can learn, in learnset order (alphabetical by id). */
export function learnsetOf(dex: TeamDex, species: DexSpecies): DexMove[] {
  return species.learnset.flatMap((i) => dex.moves[i] ?? []);
}

/** Lowercase, accent-free text for search ("Flabébé" → "flabebe"). */
export function searchKey(text: string): string {
  return text
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase();
}
